import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Basic ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='w-full h-full bg-[#110828] p-4 text-white font-poppins overflow-hidden'
      >
        {children}
      </body>
    </html>
  );
}
